import type { Metadata } from "next";
import { Ubuntu as CustomFont } from "next/font/google";
import { Badge, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { TopbarContainer } from "../components/topbar";
import { Toaster } from "react-hot-toast";

const font = CustomFont({
  weight: ["300", "400", "500", "700"],
  display: "swap",
  subsets: ["latin"],
  variable: "--custom-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = React.PropsWithChildren;

export default function RootLayout(props: Readonly<LayoutProps>) {
  const { children } = props;

  return (
    <html lang="en">
      <body className={font.className}>
        <Toaster />
        <Theme appearance="dark">
          <TopbarContainer className="flex items-center px-2">
            <Badge color="sky">ShaderX</Badge>
          </TopbarContainer>
          <ThemePanel defaultOpen={false} />
          {children}
        </Theme>
      </body>
    </html>
  );
}
